apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-core
spec:
  template:
    spec:
      containers:
        - name: backend-core
          env:
            - name: LIA_URL
              value: "https://api.production.cloud.planetlia.com"