apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-core
  namespace: planetlia-platform
spec:
  template:
    spec:
      containers:
        - name: backend-core
          env:
            - name: LIA_URL
              value: "https://api.production.cloud.planetlia.com"
            - name: LIA_ONLINE_EDITOR_MAX_CPU
              value: "6"
            - name: LIA_REDIS_HOST
              value: "redis-service"