apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../../apps/planetlia-platform/backend-core
patchesStrategicMerge:
  - deployment-patch.yaml
patchesJson6902:
  - target:
      name: backend-core
      group: networking.k8s.io
      version: v1beta1
      kind: Ingress
    path: ingress-domain-patch.yaml
  - target:
      name: backend-core
      group: apps
      version: v1
      kind: Deployment
    path: image-patch.yaml
