apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../apps/argo-cd
  - applications
patchesJson6902:
  - target:
      name: argocd-server-http-ingress
      group: networking.k8s.io
      version: v1beta1
      kind: Ingress
    path: argo-cd-http-ingress-domain-patch.yaml
  - target:
      name: argocd-server-grpc-ingress
      group: networking.k8s.io
      version: v1beta1
      kind: Ingress
    path: argo-cd-grpc-ingress-domain-patch.yaml
patchesStrategicMerge:
  - argo-cd-cm-patch.yaml