apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../../apps/planetlia_platform/backend
patchesStrategicMerge:
  - deployment-patch.yaml

patchesJson6902:
  - target:
      name: platform-backend
      group: networking.k8s.io
      version: v1beta1
      kind: Ingress
    path: ingress-domain-patch.yaml
