apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../../apps/planetlia-platform/files
resources:
  - pv.yaml
  - sc.yaml
patchesJson6902:
  - target:
      name: files
      group: networking.k8s.io
      version: v1beta1
      kind: Ingress
    path: ingress-domain-patch.yaml
    