apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-core
  labels:
    app: backend-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-core
  template:
    metadata:
      labels:
        app: backend-core
    spec:
      containers:
        - name: backend-core
          image: planetlia/backend-core:latest
          ports:
            - containerPort: 8080
          env:
            - name: LIA_URL
              value: "http://api.example.com"