apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: backend-core
  namespace: planetlia-platform
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,X-Special-Authorization"
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: backend-core-service
              servicePort: 80
      host: api.example.com
  tls:
    - hosts:
        - api.example.com
      secretName: api.example.com-secret