apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - managers
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - online-editor-k8s-auth.yaml
