apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-core-sa
  namespace: planetlia-platform
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: online-editor-matches-role
  namespace: online-editor-matches
rules:
- apiGroups: [""]
  resources: ["pods" , "pods/log", "namespace"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: backend-core-rb
  namespace: online-editor-matches
subjects:
- kind: ServiceAccount
  name: backend-core-sa
  namespace: planetlia-platform
roleRef:
  kind: Role
  name: online-editor-matches-role
  apiGroup: rbac.authorization.k8s.io

