apiVersion: v1
kind: Service
metadata:
  name: backend-core-service
  namespace: planetlia-platform
spec:
  selector:
    app: backend-core
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080