apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/planet-lia/infrastructure
    targetRevision: HEAD 
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true

  ignoreDifferences:
    - group: core
      kind: Secret
      name: argocd-secret
      namespace: argocd
      jsonPointers:
      - /data