apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../../apps/argo-cd/applications
patchesStrategicMerge:
  - argo-cd-patch.yaml
  - cert-manager-patch.yaml
  - nginx-ingress-patch.yaml
  - planetlia_platform_backend_core-patch.yaml
  - planetlia_platform_files-patch.yaml
  - planetlia_platform_redis-patch.yaml
namespace: argocd