- op: remove
  path: /spec/template/spec/containers/0/env/0/value

- op: remove
  path: /spec/template/spec/containers/0/env/1/value

- op: add
  path: /spec/template/spec/containers/0/env/0/valueFrom
  value:
    secretKeyRef:
      name: files-secret
      key: minio-access-key

- op: add
  path: /spec/template/spec/containers/0/env/1/valueFrom
  value:
    secretKeyRef:
      name: files-secret
      key: minio-secret-key
